app/models.py
from datetime import datetime, timezone
from typing import Optional
import sqlalchemy as sa
import sqlalchemy.orm as so
from app import db, login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(sa.String(64), index=True,
                                                unique=True)
    email: so.Mapped[str] = so.mapped_column(sa.String(120), index=True,
                                             unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))

    pushups: so.WriteOnlyMapped['Pushup'] = so.relationship(
        back_populates='who')

    def __repr__(self):
        return '<User {}>'.format(self.username)
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
class Pushup(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    reps: so.Mapped[int] = so.mapped_column(sa.Integer)
    timestamp: so.Mapped[datetime] = so.mapped_column(
        index=True, default=lambda: datetime.now(timezone.utc))
    user_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey(User.id),
                                               index=True)

    who: so.Mapped[User] = so.relationship(back_populates='pushups')

    def __repr__(self):
        return '<Reps {}>'.format(self.reps)
    
@login.user_loader
def load_user(id):
    return db.session.get(User, int(id))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, IntegerField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, NumberRange

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class PushupForm(FlaskForm):
    pushup_count = IntegerField('Number of pushups', default=10, validators=[DataRequired(), NumberRange(min=1, max=100)])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)
login.login_view = 'login'
moment = Moment(app)

from app import models, routes

app/routes.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user, login_required
import sqlalchemy as sa
from app import app, db
from app.models import User, Pushup
from datetime import datetime, timedelta, timezone
from app.forms import LoginForm, PushupForm
from sqlalchemy import func, desc
from zoneinfo import ZoneInfo

@app.route('/')
@app.route('/index')
def index():
    all_time_reps, all_time_sets = get_stats_all_users()

    # set default number of pushups to users average
    if current_user.is_authenticated:
        try:
            query = db.select(func.floor(func.avg(Pushup.reps))).where(Pushup.user_id == current_user.id)
            result = db.session.execute(query)
            pushup_average = result.scalars().one()
        except:
            pushup_average = 15
    else:
        pushup_average = 10
    pushup_sets = db.session.execute(db.select(Pushup).order_by(Pushup.timestamp.desc())).scalars()
    timezone = ZoneInfo('America/New_York')
    seven_days_ago = datetime.now(timezone) - timedelta(days=7)
    last_7_day_sets = db.session.query(User.username, func.count(Pushup.id).label('set_count')).select_from(User).join(Pushup).group_by(User.username).where(Pushup.timestamp >= seven_days_ago).order_by(desc('set_count'))
    form = PushupForm()
    return render_template('index.html', title='Home', pushup_sets=pushup_sets, pushup_average=pushup_average, 
                           last_7_day_sets=last_7_day_sets, all_time_reps=all_time_reps, all_time_sets=all_time_sets, form=form)



@app.route('/log_set', methods=['POST'])
@login_required
def log_set():
    pushup = Pushup(user_id = current_user.id, timestamp = datetime.now(), reps = request.form['pushup_count'])
    db.session.add(pushup)
    db.session.commit()
    flash('pushup set logged!')
    return redirect(url_for('index'))

@app.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == form.username.data)
        )
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('index'))
        
    return render_template('login.html', title='Sign In', form=form)

@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

@app.route('/user/<username>')
@login_required
def user(username):
    user = db.first_or_404(sa.select(User).where(User.username ==  username)) 
    
    query = db.session.query(func.count(Pushup.id).label('set_count')).where(Pushup.user_id == user.id)
    result = db.session.execute(query)
    all_time_sets = result.scalars().one()

    query = db.session.query(func.sum(Pushup.reps).filter(Pushup.user_id == user.id))
    result = db.session.execute(query)
    all_time_reps = result.scalars().one()

    # query = db.session.query(func.max(Pushup.reps).filter(Pushup.user_id == user.id))
    # result = db.session.execute(query)
    # print(result)
    # max_reps = result.scalars().one()
    query = db.session.query(Pushup).filter(Pushup.user_id == user.id).order_by(desc(Pushup.reps)).limit(1)
    result = db.session.execute(query)
    print(result)
    max_reps = result.scalars().one()
 
 
    return render_template('user.html', user=user, all_time_sets=all_time_sets, all_time_reps=all_time_reps, max_reps=max_reps)

def get_stats_all_users():
    query = db.session.query(func.sum(Pushup.reps).label('all_time_reps'))
    result = db.session.execute(query)
    all_time_reps = result.scalars().one()
    all_time_sets = db.session.query(func.count()).select_from(Pushup).scalar()

    return all_time_reps, all_time_sets

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pushup Tracker</title>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
      integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css')}}"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <button
          class="navbar-toggler ms-auto"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('index') }}">Pushup Tracker</a>

        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index')}}">Home</a>
          </li>
          {% if current_user.is_anonymous %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('login')}}">Login</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a
              class="nav-link"
              href="{{ url_for('user', username=current_user.username) }}"
              >Profile</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('logout')}}">Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% with messages = get_flashed_messages() %} {% if messages %} {% for
    message in messages %}
    <div class="alert alert-info">{{ message }}</div>
    {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %} {{
    moment.include_moment() }}
  </body>
</html>

app/templates/bootstrap_wtf.html
{% macro form_field(field, autofocus) %}
  {%- if field.type == 'BooleanField' %}
  <div class="form-check mb-3">
    {{ field(class='form-check-input') }}
    {{ field.label(class='form-check-label') }}
  </div>
  {%- elif field.type == 'RadioField' %}
    {{ field.label(class='form-label') }}
    {%- for item in field %}
    <div class="form-check{% if loop.last %} mb-3{% endif %}">
      {{ item(class='form-check-input') }}
      {{ item.label(class='form-check-label') }}
    </div>
    {%- endfor %}
  {%- elif field.type == 'SelectField' %}
    {{ field.label(class='form-label') }}
    {{ field(class='form-select mb-3') }}
  {%- elif field.type == 'TextAreaField' %}
  <div class="mb-3">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
  </div>
  {%- elif field.type == 'SubmitField' %}
  {{ field(class='btn btn-primary mb-3') }}
  {%- else %}
  <div class="mb-3">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
  </div>
  {%- endif %}
{% endmacro %}

{% macro quick_form(form, action="", method="post", id="", novalidate=False) %}
<form
  {%- if action != None %} action="{{ action }}"{% endif -%}
  {%- if method %} method="{{ method }}"{% endif %}
  {%- if id %} id="{{ id }}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}>
  {{ form.hidden_tag() }}
  {%- for field, errors in form.errors.items() %}
    {%- if form[field].widget.input_type == 'hidden' %}
      {%- for error in errors %}
      <div class="invalid-feedback">{{ error }}</div>
      {%- endfor %} 
    {%- endif %}
  {%- endfor %}

  {% set ns = namespace(first_field=true) %}
  {%- for field in form %}
    {% if field.widget.input_type != 'hidden' -%}
      {{ form_field(field, ns.first_field) }}
      {% set ns.first_field = false %}
    {%- endif %}
  {%- endfor %}  
</form>
{% endmacro %}

app/templates/index.html
{% extends "base.html" %} {% import 'bootstrap_wtf.html' as wtf %} {% block
content %} {% if current_user.is_anonymous %}
<h3>Log in and do a set!</h3>
{% else %}
<h3>Log a set of pushups!</h3>
<br />
<form action="/log_set" method="post" novalidate>
  {{ form.hidden_tag() }}
  <p>
    {{ form.pushup_count.label }}: {{ form.pushup_count(size=5,
    value=pushup_average) }}
  </p>
  <p>{{ form.submit() }}</p>
</form>
{% endif %}
<hr />
<div class="row">
<div class="column">
<h3>Leaderboard - Sets In Last 7 Days</h3>
<table id="sets_leaderboard">
  <tbody>
    {% for last7 in last_7_day_sets %}
    <tr></tr>
    <td>{{ last7[0] }}: </td>
    <td>{{ last7[1] }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<div class="divider"></div>
<div class="column">
  <h3>Stats - All Users</h3>
  <table id="stats_all_users">
    <tbody>
      <tr>
        <td>All Time Sets: </td>
        <td>{{ "{:,}".format(all_time_sets) }}</td>
      </tr>
      <tr>
        <td>All Time Reps: </td>
        <td>{{ "{:,}".format(all_time_reps) }}</td>
      </tr>
    </tbody>
  </table>
</div>
</div>
<div id = "stat_detail">
<hr />
<h3>Set Details - All Time</h3>
<table id="hosts" class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>When</th>
      <th>How Many</th>
    </tr>
  </thead>
  <tbody>
    {% for pushup_set in pushup_sets %}
    <tr>
      <td><a href="{{ url_for('user', username=pushup_set.who.username) }}">{{ pushup_set.who.username }}</a></td>
      <td>{{ moment(pushup_set.timestamp).format('YYYY-MM-DD h:mm a') }}</td>
      <td>{{ pushup_set.reps }}</td>
    </tr>
    {% endfor %}
  </tbody>
  {% endblock %}
</table>
</div>

app/templates/login.html
{% extends "base.html" %} {% block content %}
<h1>Sign In</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <p>
    {{ form.username.label }}<br />
    {{ form.username(size=32) }} {% for error in form.username.errors %}
    <span style="color: red">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.password.label }}<br />
    {{ form.password(size=32) }} {% for error in form.password.errors %}
    <span style="color: red">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
  <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/user.html
{% extends "base.html" %} {% block content %}
<h1>User: {{ user.username }}</h1>
<h4>All Time Sets: {{ all_time_sets }}</h4>
<h4>All Time Reps: {{ all_time_reps }}</h4>
<h4>
  Best Set: {{ max_reps.reps }} reps on {{
  moment(max_reps.timestamp).format('YYYY-MM-DD') }}
</h4>
{% endblock %}

<td>{{ moment(pushup_set.timestamp).format('YYYY-MM-DD h:mm a') }}</td>